from __future__ import annotations

import json
import re
import shutil
import subprocess
from dataclasses import dataclass

from .config import KEYS_FILE, SUBFINDER_PROVIDER_FILE, _chmod_private, ensure_layout


@dataclass(frozen=True)
class Provider:
    key: str
    label: str
    hint: str


# Superset of API-backed sources used by recent Subfinder releases.
# Runtime compatibility is checked with `subfinder -ls`, so a key for a source
# that is not supported by the installed engine is kept locally but not passed
# to Subfinder.
PROVIDERS: tuple[Provider, ...] = (
    Provider("github", "GitHub", "personal access token"),
    Provider("virustotal", "VirusTotal", "API key"),
    Provider("securitytrails", "SecurityTrails", "API key"),
    Provider("chaos", "ProjectDiscovery Chaos", "API key"),
    Provider("censys", "Censys", "API_ID:API_SECRET"),
    Provider("shodan", "Shodan", "API key"),
    Provider("binaryedge", "BinaryEdge", "API key"),
    Provider("bevigil", "BeVigil", "API key"),
    Provider("fullhunt", "FullHunt", "API key"),
    Provider("certspotter", "Cert Spotter", "API key (opsional)"),
    Provider("urlscan", "URLScan.io", "API key (opsional)"),
    Provider("netlas", "Netlas", "API key"),
    Provider("leakix", "LeakIX", "API key"),
    Provider("hackertarget", "HackerTarget", "API key (opsional)"),
    Provider("whoisxmlapi", "WhoisXML API", "API key"),
    Provider("hunter", "Hunter", "API key"),
    Provider("builtwith", "BuiltWith", "API key"),
    Provider("c99", "C99", "API key"),
    Provider("fofa", "FOFA", "EMAIL:API_KEY"),
    Provider("intelx", "Intelligence X", "HOST:API_KEY"),
    Provider("quake", "Quake", "API key"),
    Provider("robtex", "Robtex", "API key"),
    Provider("threatbook", "ThreatBook", "API key"),
    Provider("zoomeyeapi", "ZoomEye", "HOST:API_KEY"),
    Provider("dnsrepo", "DNSRepo", "API key"),
    Provider("chinaz", "Chinaz", "API key"),
)

_ANSI = re.compile(r"\x1b\[[0-9;]*m")


def _provider_keys() -> set[str]:
    return {p.key for p in PROVIDERS}


def load_keys() -> dict[str, list[str]]:
    ensure_layout()
    try:
        raw = json.loads(KEYS_FILE.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}
    result: dict[str, list[str]] = {}
    if not isinstance(raw, dict):
        return result
    for name, values in raw.items():
        if name not in _provider_keys():
            continue
        if isinstance(values, str):
            values = [values]
        if isinstance(values, list):
            clean = [str(v).strip() for v in values if str(v).strip()]
            if clean:
                result[name] = clean
    return result


def runtime_subfinder_sources(timeout: int = 12) -> set[str] | None:
    """Return API provider names supported by installed Subfinder.

    None means the engine is unavailable or its source list could not be read.
    No API secret is sent by this check.
    """
    if shutil.which("subfinder") is None:
        return None
    try:
        proc = subprocess.run(
            ["subfinder", "-ls"],
            capture_output=True,
            text=True,
            timeout=timeout,
            check=False,
        )
    except (OSError, subprocess.SubprocessError):
        return None
    text = _ANSI.sub("", (proc.stdout or "") + "\n" + (proc.stderr or "")).lower()
    if not text.strip():
        return None
    supported: set[str] = set()
    for provider in PROVIDERS:
        if re.search(rf"(?<![a-z0-9_-]){re.escape(provider.key)}(?![a-z0-9_-])", text):
            supported.add(provider.key)
    return supported


def provider_status() -> list[dict[str, object]]:
    keys = load_keys()
    runtime = runtime_subfinder_sources()
    rows: list[dict[str, object]] = []
    for provider in PROVIDERS:
        rows.append({
            "key": provider.key,
            "label": provider.label,
            "configured": provider.key in keys,
            "supported": None if runtime is None else provider.key in runtime,
        })
    return rows


def save_keys(keys: dict[str, list[str]]) -> None:
    ensure_layout()
    filtered = {k: v for k, v in keys.items() if k in _provider_keys() and v}
    tmp = KEYS_FILE.with_suffix(".tmp")
    tmp.write_text(json.dumps(filtered, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    tmp.replace(KEYS_FILE)
    _chmod_private(KEYS_FILE)
    write_subfinder_provider_config(filtered)


def write_subfinder_provider_config(keys: dict[str, list[str]] | None = None) -> None:
    ensure_layout()
    keys = keys if keys is not None else load_keys()
    runtime = runtime_subfinder_sources()
    lines = ["# Generated by Cyber Tool By Wynn. Do not share this file."]
    # Only write configured providers. If Subfinder can report its runtime
    # sources, skip providers unsupported by that installed release.
    for provider in PROVIDERS:
        values = keys.get(provider.key, [])
        if not values:
            continue
        if runtime is not None and provider.key not in runtime:
            continue
        lines.append(f"{provider.key}:")
        for value in values:
            lines.append("  - " + json.dumps(value, ensure_ascii=False))
    tmp = SUBFINDER_PROVIDER_FILE.with_suffix(".tmp")
    tmp.write_text("\n".join(lines) + "\n", encoding="utf-8")
    tmp.replace(SUBFINDER_PROVIDER_FILE)
    _chmod_private(SUBFINDER_PROVIDER_FILE)


def set_key(provider: str, value: str) -> None:
    provider = provider.strip().lower()
    if provider not in _provider_keys():
        raise ValueError("Provider tidak dikenal")
    value = value.strip()
    if not value:
        raise ValueError("API key kosong")
    keys = load_keys()
    keys[provider] = [value]
    save_keys(keys)


def remove_key(provider: str) -> None:
    keys = load_keys()
    keys.pop(provider.strip().lower(), None)
    save_keys(keys)


def configured() -> list[str]:
    return sorted(load_keys())


def usable_configured() -> list[str]:
    names = configured()
    runtime = runtime_subfinder_sources()
    if runtime is None:
        return names
    return sorted(set(names).intersection(runtime))


def masked(provider: str) -> str:
    values = load_keys().get(provider, [])
    if not values:
        return "belum diatur"
    value = values[0]
    if len(value) <= 8:
        return "••••••••"
    return f"{value[:4]}…{value[-4:]}"
