from __future__ import annotations

import json
from dataclasses import dataclass

from .config import KEYS_FILE, SUBFINDER_PROVIDER_FILE, _chmod_private, ensure_layout


@dataclass(frozen=True)
class Provider:
    key: str
    label: str
    hint: str


# Keep this registry aligned with current Subfinder provider names.  Unknown or
# retired sources are intentionally not written to provider-config.yaml so an
# old key cannot break a future scan.
PROVIDERS: tuple[Provider, ...] = (
    Provider("github", "GitHub", "personal access token"),
    Provider("virustotal", "VirusTotal", "API key"),
    Provider("securitytrails", "SecurityTrails", "API key"),
    Provider("chaos", "ProjectDiscovery Chaos", "API key"),
    Provider("urlscan", "URLScan.io", "API key (opsional)"),
    Provider("netlas", "Netlas", "API key"),
    Provider("leakix", "LeakIX", "API key"),
    Provider("hackertarget", "HackerTarget", "API key (opsional)"),
    Provider("whoisxmlapi", "WhoisXML API", "API key"),
    Provider("censys", "Censys", "API_ID:API_SECRET"),
    Provider("shodan", "Shodan", "API key"),
    Provider("binaryedge", "BinaryEdge", "API key"),
    Provider("bevigil", "BeVigil", "API key"),
    Provider("fullhunt", "FullHunt", "API key"),
    Provider("certspotter", "Cert Spotter", "API key (opsional)"),
)


def _provider_keys() -> set[str]:
    return {p.key for p in PROVIDERS}


def load_keys() -> dict[str, list[str]]:
    ensure_layout()
    try:
        raw = json.loads(KEYS_FILE.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}
    result: dict[str, list[str]] = {}
    if not isinstance(raw, dict):
        return result
    for name, values in raw.items():
        if name not in _provider_keys():
            continue
        if isinstance(values, str):
            values = [values]
        if isinstance(values, list):
            clean = [str(v).strip() for v in values if str(v).strip()]
            if clean:
                result[name] = clean
    return result


def save_keys(keys: dict[str, list[str]]) -> None:
    ensure_layout()
    filtered = {k: v for k, v in keys.items() if k in _provider_keys() and v}
    tmp = KEYS_FILE.with_suffix(".tmp")
    tmp.write_text(json.dumps(filtered, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    tmp.replace(KEYS_FILE)
    _chmod_private(KEYS_FILE)
    write_subfinder_provider_config(filtered)


def write_subfinder_provider_config(keys: dict[str, list[str]] | None = None) -> None:
    ensure_layout()
    keys = keys if keys is not None else load_keys()
    lines = ["# Generated by Cyber Tool By Wynn. Do not share this file."]
    for provider in PROVIDERS:
        values = keys.get(provider.key, [])
        lines.append(f"{provider.key}:")
        for value in values:
            lines.append("  - " + json.dumps(value, ensure_ascii=False))
    tmp = SUBFINDER_PROVIDER_FILE.with_suffix(".tmp")
    tmp.write_text("\n".join(lines) + "\n", encoding="utf-8")
    tmp.replace(SUBFINDER_PROVIDER_FILE)
    _chmod_private(SUBFINDER_PROVIDER_FILE)


def set_key(provider: str, value: str) -> None:
    provider = provider.strip().lower()
    if provider not in _provider_keys():
        raise ValueError("Provider tidak dikenal")
    value = value.strip()
    if not value:
        raise ValueError("API key kosong")
    keys = load_keys()
    keys[provider] = [value]
    save_keys(keys)


def remove_key(provider: str) -> None:
    keys = load_keys()
    keys.pop(provider.strip().lower(), None)
    save_keys(keys)


def configured() -> list[str]:
    return sorted(load_keys())


def masked(provider: str) -> str:
    values = load_keys().get(provider, [])
    if not values:
        return "belum diatur"
    value = values[0]
    if len(value) <= 8:
        return "••••••••"
    return f"{value[:4]}…{value[-4:]}"
